### ISSUE TITLE
[Feature Request] Scrape course data

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/courses-api#2]
### Overview

Create a web scraper to extract course data from the UofA course planner website: https://courseplanner.uni.adelaide.edu.au. 

### Details

- Scrape UofA course data using their API.
- Schedule regular scraping for updated data, probably once a month and/or before running own API server.
- Store scraped data in a database.
- Needs to do the following: 
  - Get all subjects
  - Get all subjects by year and semester
  - Search courses by subject (e.g., COMP SCI), number (e.g., 2103) and course title (e.g., Algorithm Design & Data Structures) 
  - Get course details using course id (e.g, 107592)
  - Get course class list using course id (e.g, 107592)
  - Get class info (like time, size, enrolled, and available seats) by class number (e.g, 11472)

### Why would this feature be useful?

Scrapes course data needed for other projects.

### Additional Notes

**NOTE: https://www.adelaide.edu.au/webteam/dfsearch/2024 was used to obtain some of these links**

**get subjects by year**
e.g. https://courseplanner-api.adelaide.edu.au/api/course-planner-query/v1/?target=/system/SUBJECTS_BY_YEAR/queryx&virtual=Y&year_from=2024&year_to=2024

then

**from each of the "SUBJECT" fields, use this to do course search**
e.g. https://courseplanner-api.adelaide.edu.au/api/course-planner-query/v1/?target=/system/COURSE_SEARCH/queryx&virtual=Y&year=2024&subject=COMP%20SCI&pagenbr=1&pagesize=500

then

**from "COURSE_ID" field, use this to do course detail search**
e.g. https://courseplanner-api.adelaide.edu.au/api/course-planner-query/v1/?target=/system/COURSE_DTL/queryx&virtual=Y&year=2024&courseid=107592&term=4410

then

**use "COURSE_ID" field, use this to get course class list**
e.g. https://courseplanner-api.adelaide.edu.au/api/course-planner-query/v1/?target=/system/COURSE_CLASS_LIST/queryx&virtual=Y&crseid=107592&offer=1&term=4410&session=1

---

**You can search by terms** - use this mainly for determining term codes
e.g. https://courseplanner-api.adelaide.edu.au/api/course-planner-query/v1/?target=/system/TERMS/queryx&virtual=Y&year_from=2024&year_to=2024

---

![image](https://github.com/user-attachments/assets/346272c4-3192-4bdb-b539-1a475c5e470d)

**Comment by Kingteena** [comment]
Hey I think I can help out! Please assign me on the project
