### ISSUE TITLE
[Bug] Adding summer or winter courses shows a blank page

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/courses-api#20]
### Description of the Bug

Adding summer or winter courses shows a blank page.

### Reproduction Steps

Select summer school, business, business 200 and it will crash.

### Expected Behaviour

Should work normally and show the classes.

### Additional Notes

<img width="494" alt="image" src="https://github.com/user-attachments/assets/614e0478-8ed3-43d6-8f7e-18da0ee0cc8c">

**Comment by jsun969** [comment]
solved #23
