### ISSUE TITLE
[Bug] Weekend classes causes a 501 error.

### ISSUE THREAD

**Issue by xxori** [compsci-adl/courses-api#40]
### Description of the Bug

The pydantic schema has literals hardcoded for weekdays only, but some classes (for example, [ELEC ENG 3088 - Computer Architecture](https://access.adelaide.edu.au/courses/details.asp?year=2024&course=110989+1+4410+1)), have some weekend classes, causing an error.

### Reproduction Steps

Add ELEC ENG 3088 - Computer Architecture as a class.

### Expected Behaviour

The course will add successfully without erroring.

### Additional Notes

The timetable only shows weekdays. in the case of computer architecture, the page says to ignore the weekend assessment as it doesn't exist in 2024. I think dropping this weekend slot is fine in this case, but some courses may utilise the weekend slots for assessments.

**Comment by jsun969** [comment]
Get rid of the class from that course to make it valid.
