### ISSUE TITLE
[Feature Request] Switch to uv and ruff

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/courses-api#42]
### Overview

Use **uv** as a package and project manager and **ruff** as a linter and code formatter.

### Details

- Replace **Poetry** with **uv** as the package and project manager since it's written in Rust and thus way faster.
- Replace **Black** with **ruff** as a linter and code formatter since it's also written in Rust and way faster.
- Update workflows to use **uv** and **ruff**

### Why would this feature be useful?

To improve the speed for installing dependencies, and linting and formatting code.

**Comment by Shr1ftyy** [comment]
yes 🤝
