### ISSUE TITLE
[Bug] db.json filepath

### ISSUE THREAD

**Issue by SouthernPolaris** [compsci-adl/courses-api#51]
### Description of the Bug

db.json saves to outside src when run

### Reproduction Steps

uv run fastapi dev src/server.py
uv run python3 src/scraper.py

### Expected Behaviour

db.json inside src should be modified or created if it does not already exist

### Additional Notes

There are now 2 db.json, one inside and outside src

**Comment by rayokamoto** [comment]
#60 makes this issue obsolete
