### ISSUE TITLE
[Feature Request] Add calendar download for selected courses

### ISSUE THREAD

**Issue by hughmancoder** [compsci-adl/courses-api#7]
### Overview

Generate ICS file or live calendar feed list for selected courses for a given semester. 

Input
Course Name or Couse Code, Year 

Output
.ics (calendar) file with corresponding courses and times

### Details

Add class locations to calendar notes

### Why would this feature be useful?

I manually enter my classes into my calendar which is inconvenient.
MyUni or course planner do not offer this feature.

**Comment by jsun969** [comment]
Please use https://github.com/jsun969/audit-monkey or https://github.com/rayokamoto/AUDIT

**Comment by phoenixpereira** [comment]
We can probably still implement this, but it may be better suited for MyTimetable which has a UI for it.

**Comment by jsun969** [comment]
IMO the calendar should be generated from myadelaide not our project, bc our timetable is not the final enrolment.
